version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_NAME=shortenerdb
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - BASE_URL=http://localhost:3000
    command: npm run dev

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shortenerdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
